name: Unity Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Unity Unit Tests
    runs-on: ubuntu-latest

    steps:
      #Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      #Cache Unity activation and dependencies
      - name: Cache Unity
        uses: actions/cache@v4
        with:
          path: ~/.local/share/unity3d
          key: ${{ runner.os }}-unity
          restore-keys: |
            ${{ runner.os }}-unity

      #Run Unity tests (EditMode + PlayMode)
      - name: Run Unity Tests
        uses: game-ci/unity-test-runner@v4
        with:
          projectPath: .
          unityVersion: 2022.3.41f1 #Github version
          testMode: all
          artifactsPath: test-results
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          
      #Uploads test results to GitHub
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: unity-test-results
          path: test-results
          
      #Publish test summary to GitHub Actions UI
      - name: Report Test Results to GitHub Summary
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: test-results/**/*.xml
